# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
np.__version__

'2.3.4'

In [8]:
np.show_config()

Build Dependencies:
  blas:
    detection method: system
    found: true
    include directory: unknown
    lib directory: unknown
    name: accelerate
    openblas configuration: unknown
    pc file directory: unknown
    version: unknown
  lapack:
    detection method: system
    found: true
    include directory: unknown
    lib directory: unknown
    name: accelerate
    openblas configuration: unknown
    pc file directory: unknown
    version: unknown
Compilers:
  c:
    commands: cc
    linker: ld64
    name: clang
    version: 15.0.0
  c++:
    commands: c++
    linker: ld64
    name: clang
    version: 15.0.0
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.1.4
Machine Information:
  build:
    cpu: aarch64
    endian: little
    family: aarch64
    system: darwin
  host:
    cpu: aarch64
    endian: little
    family: aarch64
    system: darwin
Python Information:
  path: /private/var/folders/y6/nj790rtn62lfktb1sh__79hc0000gn/T/build-env-krvc8

#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
x = np.zeros(shape=(10))  # np.zeros(10)
print(x)
print(len(x))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
10


#### 4. How to find the memory size of any array (★☆☆)

In [18]:
a = np.array([1], dtype='int')

print(a.size * a.itemsize, x.size * x.itemsize)

8 80


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [24]:
# print(np.add.__doc__)

! python -c "import numpy as np; np.info(np.add)"

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

In [25]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [26]:
nulls = np.zeros(10)
nulls[4] = 1

nulls

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [30]:
nums = np.arange(start=10, stop=50)
nums

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [32]:
reversed_nums = nums[::-1]
reversed_nums

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [38]:
mat = np.arange(0, 9).reshape(3, 3)
mat

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [44]:
arr = np.array([1,2,0,0,4,0])

indices = np.where(arr != 0)
indices

(array([0, 1, 4]),)

In [45]:
# built-in

np.nonzero(arr)

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [55]:
# identity_mat = np.identity(3)
identity_mat = np.eye(3)

print(identity_mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [56]:
np.info(np.eye)

 eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, device=None,
     like=None)

Return a 2-D array with ones on the diagonal and zeros elsewhere.

Parameters
----------
N : int
  Number of rows in the output.
M : int, optional
  Number of columns in the output. If None, defaults to `N`.
k : int, optional
  Index of the diagonal: 0 (the default) refers to the main diagonal,
  a positive value refers to an upper diagonal, and a negative value
  to a lower diagonal.
dtype : data-type, optional
  Data-type of the returned array.
order : {'C', 'F'}, optional
    Whether the output should be stored in row-major (C-style) or
    column-major (Fortran-style) order in memory.
device : str, optional
    The device on which to place the created array. Default: None.
    For Array-API interoperability only, so must be ``"cpu"`` if passed.

    .. versionadded:: 2.0.0
like : array_like, optional
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [67]:
randoms = np.random.random(size=(3, 3, 3))
randoms

array([[[0.57314079, 0.6053847 , 0.81604051],
        [0.37100194, 0.15986435, 0.72807533],
        [0.62289703, 0.03398804, 0.10648266]],

       [[0.74566476, 0.49031593, 0.46895778],
        [0.6202886 , 0.32231698, 0.18607289],
        [0.45887747, 0.32951264, 0.46868689]],

       [[0.00105181, 0.30929716, 0.52147102],
        [0.79813065, 0.14596524, 0.58670549],
        [0.6776558 , 0.93290637, 0.23503515]]])

In [63]:
np.info(np.random.random)

 random(size=None)

random(size=None)

Return random floats in the half-open interval [0.0, 1.0). Alias for
`random_sample` to ease forward-porting to the new random API.


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [72]:
rand_mat = np.random.random(size=(10, 10))

print(rand_mat)
print(np.min(rand_mat))
print(np.max(rand_mat))

[[0.22323539 0.09334814 0.8812998  0.84372221 0.8975154  0.75629494
  0.79815383 0.72235116 0.71709291 0.70641593]
 [0.22493094 0.9456477  0.36903566 0.9569429  0.15813437 0.88071753
  0.65471983 0.50893048 0.18153469 0.09917014]
 [0.08886465 0.61901262 0.10909727 0.08138033 0.4521022  0.85511555
  0.24076011 0.17832064 0.84337114 0.91989174]
 [0.53610319 0.58918297 0.7485366  0.12867609 0.17566253 0.09419998
  0.52037519 0.78996105 0.91554163 0.6206956 ]
 [0.82105709 0.97188124 0.36734041 0.47050821 0.14623471 0.10770663
  0.65552421 0.20369257 0.97916267 0.36022864]
 [0.30730205 0.89294409 0.59600006 0.12300443 0.42035444 0.71625452
  0.07839636 0.95223991 0.62440471 0.85234568]
 [0.77498535 0.10750577 0.39897427 0.73500613 0.55282595 0.17898985
  0.33000654 0.87179181 0.00336262 0.0898785 ]
 [0.30527164 0.67451274 0.1279797  0.6930968  0.57292671 0.12570333
  0.6297166  0.23028103 0.78134773 0.80925887]
 [0.6520793  0.05411355 0.86951373 0.16495684 0.40138089 0.56651183
  0.01586638

In [73]:
rand_mat = np.random.randint(1, 50, size=(10, 10))

print(rand_mat)
print(np.min(rand_mat))
print(np.max(rand_mat))

[[34 29  1 11  9 19 31 46  1 45]
 [28  9 28 49 21 22  5 31  7  5]
 [44 35 46 36 47 26 19 44 13 13]
 [14 44 36 29 41  3  3 41 42 21]
 [20  3 25 48 41 15 13 47 34  3]
 [27 26  1 15 31 34 49  6 12 15]
 [39 21 15 25 27 37  4 24 37 49]
 [26 40 24 28 41  6 11 16 41 47]
 [47 47 40 49  2 21 14 10  1 47]
 [36 40  2  1 42 34 13 27  8 41]]
1
49


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [78]:
z = np.random.randint(1, 10, size=30)
print(z)
print(np.mean(z))
print(z.mean())

[1 4 4 8 7 1 8 2 7 4 6 1 3 2 8 8 5 2 7 1 1 9 7 3 7 3 6 7 2 4]
4.6
4.6


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [90]:
"""
[111]
[101]
[111]
"""

size = 5
x = np.ones(shape=(size,size))
x[1:-1, 1:-1] = 0

x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [101]:
size = 3

arr = np.random.randint(2,7, size=(size,size))
arr = np.pad(arr, pad_width=1, mode="constant", constant_values=0)

arr

array([[0, 0, 0, 0, 0],
       [0, 2, 2, 5, 0],
       [0, 6, 3, 2, 0],
       [0, 2, 6, 6, 0],
       [0, 0, 0, 0, 0]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
"""
nan
false
false
nan
true
false
"""

print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [ ]:
mat = np.zeros(shape=(5,5))

"""
1 at row 1, col 0
2 at row 2, col 1
3 at row 3, col 2
4 at row 4, col 3
"""

arr = np.arange(1, 5)

# broadcasting
mat[arr, arr-1] = arr

mat

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.]])

In [118]:
# another easy way

arr = np.arange(1, 5)

z = np.diag(arr, k=-1)
z

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
checkerboard = np.zeros(shape=(8, 8))

"""
0 2 4 6 => 1's.   row = 0
1 3 5 7 => 1's.   row = 1 
0 2 4 6 => 1's    row = 2
"""

arr = np.arange(8)

checkerboard[::2, 1::2] = 1
checkerboard[1::2, ::2] = 1

checkerboard

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [131]:
arr = np.random.randint(1, 10, size=(6, 7, 8))

# (1,5,3)

arr[1,5,3]

print(np.unravel_index(99, shape=(6, 7, 8)))

(np.int64(1), np.int64(5), np.int64(3))


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [137]:
checkerboard = np.array([[0, 1], [1, 0]])

np.tile(checkerboard, (4, 4))


array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [144]:
x = np.random.randint(1, 10, size=(5,5))

np.linalg.norm(x)

np.float64(27.459060435491963)

In [145]:
"""
x-mean/std
"""

x = (x - x.mean()) / x.std()
x

array([[-0.3493384 , -1.54026476,  1.23856342, -0.74631385, -0.3493384 ],
       [-1.54026476,  0.04763705, -0.74631385, -1.14328931,  1.23856342],
       [ 0.44461251,  0.84158796,  1.63553887,  1.63553887, -1.14328931],
       [ 0.84158796,  0.84158796, -1.14328931, -0.74631385,  0.84158796],
       [-0.3493384 , -0.3493384 ,  0.84158796, -1.14328931,  0.84158796]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [148]:
rgba = np.dtype([("r", np.ubyte), ("g", np.ubyte), ("b", np.ubyte), ("a", np.ubyte)])
rgba

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [146]:
mat1 = np.random.randint(1, 10, size=(5,3))
mat2 = np.random.randint(1, 10, size=(3,2))

print(mat1)
print(mat2)

mat1.dot(mat2)  # or np.dot(mat1, mat2) or mat1 @ mat2

[[1 3 7]
 [2 3 9]
 [3 9 3]
 [3 4 3]
 [7 2 3]]
[[5 1]
 [6 3]
 [2 6]]


array([[37, 52],
       [46, 65],
       [75, 48],
       [45, 33],
       [53, 31]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [154]:
np.random.seed(0)
x = np.random.randint(1, 10, size=10)
x

array([6, 1, 4, 4, 8, 4, 6, 3, 5, 8])

In [ ]:
np.where((x>=3) & (x<=8), x*-1, x)

array([-6,  1, -4, -4, -8, -4, -6, -3, -5, -8])

In [161]:
x[(x>=3) & (x<=8)] *= -1
x

array([-6,  1, -4, -4, -8, -4, -6, -3, -5, -8])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [164]:
sum(range(5))

np.int64(10)

In [162]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [166]:
Z = np.arange(5)
Z**Z

array([  1,   1,   4,  27, 256])

In [167]:
2 << Z >> 2

array([0, 1, 2, 4, 8])

In [ ]:
2 << Z

"""
0000 -> 0010
0001 -> 0100
0010 -> 1000
0100 -> 10000
"""

array([ 2,  4,  8, 16, 32])

In [168]:
Z <- Z

array([False, False, False, False, False])

In [169]:
1j * Z

array([0.+0.j, 0.+1.j, 0.+2.j, 0.+3.j, 0.+4.j])

In [170]:
Z/1/1

array([0., 1., 2., 3., 4.])

In [171]:
Z < Z > Z

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [173]:
print(np.array(0) / np.array(0))

nan


/var/folders/nm/srw3ygl55jbgpddqwgysqjpm0000gn/T/ipykernel_45556/4120864939.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))


In [174]:
print(np.array(0) // np.array(0))

0


/var/folders/nm/srw3ygl55jbgpddqwgysqjpm0000gn/T/ipykernel_45556/4108562882.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


In [175]:
print(np.array([np.nan]).astype(int).astype(float))

[0.]


/var/folders/nm/srw3ygl55jbgpddqwgysqjpm0000gn/T/ipykernel_45556/3034665705.py:1: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ? (★☆☆)

In [182]:
z = np.random.random(5)

print(z)
print(np.ceil(z))
print(np.where(z>0, np.ceil(z), np.floor(z)))

[0.46147936 0.78052918 0.11827443 0.63992102 0.14335329]
[1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1.]


#### 30. How to find common values between two arrays? (★☆☆)

In [184]:
a = np.arange(1, 10)
b = np.arange(5, 10)

print(np.intersect1d(a, b))

[5 6 7 8 9]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
# np.seterr(all="ignore")

# back to safety defaults
# np.seterr(all="warn")

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [186]:
np.sqrt(-1)

/var/folders/nm/srw3ygl55jbgpddqwgysqjpm0000gn/T/ipykernel_45556/3438155168.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1)


np.float64(nan)

In [ ]:
np.emath.sqrt(-1)

"""
False
"""

np.complex128(1j)

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [210]:
from datetime import datetime, timedelta

today = datetime.now()
print(today)

yesterday = today - timedelta(days=1)
print(yesterday)

tomorrow = today + timedelta(days=1)
print(tomorrow)

2025-10-25 14:48:22.985372
2025-10-24 14:48:22.985372
2025-10-26 14:48:22.985372


In [200]:
np.info(np.datetime64)

 datetime64()

If created from a 64-bit integer, it represents an offset from
``1970-01-01T00:00:00``.
If created from string, the string can be in ISO 8601 date
or datetime format.

When parsing a string to create a datetime object, if the string contains
a trailing timezone (A 'Z' or a timezone offset), the timezone will be
dropped and a User Warning is given.

Datetime64 objects should be considered to be UTC and therefore have an
offset of +0000.

>>> np.datetime64(10, 'Y')
np.datetime64('1980')
>>> np.datetime64('1980', 'Y')
np.datetime64('1980')
>>> np.datetime64(10, 'D')
np.datetime64('1970-01-11')

See :ref:`arrays.datetime` for more information.

:Character code: ``'M'``


Methods:

  all  --  Scalar method identical to the corresponding array attribute.
  any  --  Scalar method identical to the corresponding array attribute.
  argmax  --  Scalar method identical to the corresponding array attribute.
  argmin  --  Scalar method identical to the corresponding array attribute.
 

In [209]:
today = np.datetime64("today", "D")
yesterday = today - np.timedelta64("1", "D")
tomorrow = today + np.timedelta64("1", "D")

print(today)
print(yesterday)
print(tomorrow)

2025-10-25
2025-10-24
2025-10-26


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [212]:
# np.datetime64("2016-07")

np.arange(np.datetime64("2016-07"), np.datetime64("2016-08"), dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

In [213]:
np.arange("2016-07", "2016-08", dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [223]:
np.random.seed(42)

A = np.ones(5) * 1
B = np.ones(5) * 2

print(A, B)

# np.dot(A+B, -A/2)

np.multiply(np.add(A, B, out=B), np.divide(-A, 2, out=A), out=A)

[1. 1. 1. 1. 1.] [2. 2. 2. 2. 2.]


array([-1.5, -1.5, -1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [235]:
np.random.seed(0)

arr = np.random.random(size=5) * 5
print(arr)

# method 1
print(arr // 1)

# method 2
print(np.floor(arr))

# method 3
print(arr.astype(int))

# method 4
print(arr - arr%1)


[2.74406752 3.57594683 3.01381688 2.72441591 2.118274  ]
[2. 3. 3. 2. 2.]
[2. 3. 3. 2. 2.]
[2 3 3 2 2]
[2. 3. 3. 2. 2.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [237]:
matrix = np.tile(np.arange(0, 5), reps=(5, 1))

matrix

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [246]:
def generate():
    for x in range(10):
        yield x

np.fromiter(generate(), dtype="float", count=-1)  # count says how much data is read, -1 means all of it is read

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [245]:
np.info(np.fromiter)

fromiter(iter, dtype, count=-1, *, like=None)

Create a new 1-dimensional array from an iterable object.

Parameters
----------
iter : iterable object
    An iterable object providing data for the array.
dtype : data-type
    The data-type of the returned array.

    .. versionchanged:: 1.23
        Object and subarray dtypes are now supported (note that the final
        result is not 1-D for a subarray dtype).

count : int, optional
    The number of items to read from *iterable*.  The default is -1,
    which means all data is read.
like : array_like, optional
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of an array object
    compatible with that passed in via this argument.

    .. versionadded:: 1.20.0

Returns
-------
out : ndarray
    The output array.

Notes
-----
Specify `co

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [254]:
x = np.random.random(size=10) # but this can include 0.0

# correct way
x = np.linspace(start=0, stop=1, num=11, endpoint=False)[1:]
x


array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [258]:
x = np.random.random(size=10)
print(x)

print(np.sort(x))

[0.39650574 0.8811032  0.58127287 0.88173536 0.69253159 0.72525428
 0.50132438 0.95608363 0.6439902  0.42385505]
[0.39650574 0.42385505 0.50132438 0.58127287 0.6439902  0.69253159
 0.72525428 0.8811032  0.88173536 0.95608363]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [261]:
arr = np.array([1, 2, 3, 4])

print(np.sum(arr, axis=0))
print(np.cumsum(arr, axis=0)[-1])

10
10


In [262]:
np.add.reduce.__doc__

"reduce(array, axis=0, dtype=None, out=None, keepdims=False, initial=<no value>, where=True)\n\n    Reduces `array`'s dimension by one, by applying ufunc along one axis.\n\n    Let :math:`array.shape = (N_0, ..., N_i, ..., N_{M-1})`.  Then\n    :math:`ufunc.reduce(array, axis=i)[k_0, ..,k_{i-1}, k_{i+1}, .., k_{M-1}]` =\n    the result of iterating `j` over :math:`range(N_i)`, cumulatively applying\n    ufunc to each :math:`array[k_0, ..,k_{i-1}, j, k_{i+1}, .., k_{M-1}]`.\n    For a one-dimensional array, reduce produces results equivalent to:\n    ::\n\n     r = op.identity # op = ufunc\n     for i in range(len(A)):\n       r = op(r, A[i])\n     return r\n\n    For example, add.reduce() is equivalent to sum().\n\n    Parameters\n    ----------\n    array : array_like\n        The array to act on.\n    axis : None or int or tuple of ints, optional\n        Axis or axes along which a reduction is performed.\n        The default (`axis` = 0) is perform a reduction over the first\n      

In [ ]:
np.add.reduce(arr)  # why is this faster than np.sum?

np.int64(10)

#### 42. Consider two random arrays A and B, check if they are equal (★★☆)

In [ ]:
A = np.array([1, 1, 3])
B  = np.array([1, 1, 3.1])

print(A == B)
print(np.equal(A, B))

print(np.all(A==B))
print(np.array_equal(A, B))
print(np.allclose(A, B, rtol=0.1))   # checks equality within a tolerance 

[ True  True False]
[ True  True False]
False
False
True


#### 43. Make an array immutable (read-only) (★★☆)

In [ ]:
arr = np.array([1, 2, 3, 4])
arr.flags.writeable = False

arr[0] = [2] # cannot assign val

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [290]:
"""
Polar to Cartesian:

x = r cos(θ)
y = r sin(θ)

Cartesian to Polar:

r = √(x² + y²)
θ = arctan(y/x)
"""
np.random.seed(42)

matrix = np.random.randint(1, 10, size=(10, 2)).astype("float")

r = np.sqrt(np.sum(np.power(matrix, 2), axis=1))

X, Y = matrix[:, 0], matrix[:, 1]
theta = np.arctan(Y, X)

print(matrix)
print(r)
print(theta)

polar_coords = np.column_stack((r, theta))
print(polar_coords)

[[1.32581766 4.        ]
 [1.37340077 5.        ]
 [1.24904577 3.        ]
 [1.44644133 8.        ]
 [1.32581766 4.        ]
 [1.44644133 8.        ]
 [1.40564765 6.        ]
 [1.10714872 2.        ]
 [1.40564765 6.        ]
 [1.37340077 5.        ]]
[ 8.06225775  9.43398113  7.61577311 10.63014581  6.40312424 11.3137085
  6.70820393  5.38516481 10.          5.38516481]
[1.32581766 1.37340077 1.24904577 1.44644133 1.32581766 1.44644133
 1.40564765 1.10714872 1.40564765 1.37340077]
[[ 8.06225775  1.32581766]
 [ 9.43398113  1.37340077]
 [ 7.61577311  1.24904577]
 [10.63014581  1.44644133]
 [ 6.40312424  1.32581766]
 [11.3137085   1.44644133]
 [ 6.70820393  1.40564765]
 [ 5.38516481  1.10714872]
 [10.          1.40564765]
 [ 5.38516481  1.37340077]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [304]:
np.random.seed(0)
arr = np.random.random(size=10)
arr[0] = 10
arr[5] = 10

print(arr)

# arr[np.argmax(arr)] = 0 # but only for a single max value

np.where(arr==arr.max(), 0, arr)

[10.          0.71518937  0.60276338  0.54488318  0.4236548  10.
  0.43758721  0.891773    0.96366276  0.38344152]


array([0.        , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ,
       0.        , 0.43758721, 0.891773  , 0.96366276, 0.38344152])

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [313]:
Z = np.zeros(shape=(5,5), dtype=[("x", "float"), ("y", "float")])

Z["x"] = np.linspace(0, 1, 5)
Z["y"] = np.linspace(0, 1, 5)

print(Z)

[[(0.  , 0.  ) (0.25, 0.25) (0.5 , 0.5 ) (0.75, 0.75) (1.  , 1.  )]
 [(0.  , 0.  ) (0.25, 0.25) (0.5 , 0.5 ) (0.75, 0.75) (1.  , 1.  )]
 [(0.  , 0.  ) (0.25, 0.25) (0.5 , 0.5 ) (0.75, 0.75) (1.  , 1.  )]
 [(0.  , 0.  ) (0.25, 0.25) (0.5 , 0.5 ) (0.75, 0.75) (1.  , 1.  )]
 [(0.  , 0.  ) (0.25, 0.25) (0.5 , 0.5 ) (0.75, 0.75) (1.  , 1.  )]]


In [ ]:
# example usage
Z_3d = np.zeros(shape=(5,5), dtype=[("x", int), ("y", int), ("z", int)])
Z_3d

array([[(0, 0, 0), (0, 0, 0), (0, 0, 0), (0, 0, 0), (0, 0, 0)],
       [(0, 0, 0), (0, 0, 0), (0, 0, 0), (0, 0, 0), (0, 0, 0)],
       [(0, 0, 0), (0, 0, 0), (0, 0, 0), (0, 0, 0), (0, 0, 0)],
       [(0, 0, 0), (0, 0, 0), (0, 0, 0), (0, 0, 0), (0, 0, 0)],
       [(0, 0, 0), (0, 0, 0), (0, 0, 0), (0, 0, 0), (0, 0, 0)]],
      dtype=[('x', '<i8'), ('y', '<i8'), ('z', '<i8')])

In [312]:
np.info(np.zeros)

zeros(shape, dtype=float, order='C', *, like=None)

Return a new array of given shape and type, filled with zeros.

Parameters
----------
shape : int or tuple of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    The desired data-type for the array, e.g., `numpy.int8`.  Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: 'C'
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.
like : array_like, optional
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of an array object
    compatible with that passed in via this argument.

    .. versionadded:: 1.20.0

Returns
-------
out : ndarray
    Array of zeros with the given shape, dtype, and order.

See Also
--------

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [ ]:
X = np.arange(1, 5)
Y = X + 0.5

C = 1/ np.subtract.outer(X, Y)

print(C)
print(C.shape)

[[-2.         -0.66666667 -0.4        -0.28571429]
 [ 2.         -2.         -0.66666667 -0.4       ]
 [ 0.66666667  2.         -2.         -0.66666667]
 [ 0.4         0.66666667  2.         -2.        ]]
(4, 4)


In [337]:
X = np.arange(1, 5)
Y = X + 0.5
# (4, 1). newaxis is similar to None
C = 1 / (X[:, np.newaxis] - Y)
print(C)

[[-2.         -0.66666667 -0.4        -0.28571429]
 [ 2.         -2.         -0.66666667 -0.4       ]
 [ 0.66666667  2.         -2.         -0.66666667]
 [ 0.4         0.66666667  2.         -2.        ]]


#### 48. Print the minimum and maximum representable values for each numpy scalar type (★★☆)

In [345]:
print(np.iinfo(np.int8).min)
print(np.iinfo(np.int8).max)

print(np.iinfo(np.int16).min)
print(np.iinfo(np.int16).max)

print(np.iinfo(np.int32).min)
print(np.iinfo(np.int32).max)

print(np.finfo(np.float32).min)
print(np.finfo(np.float32).max)

-128
127
-32768
32767
-2147483648
2147483647
-3.4028235e+38
3.4028235e+38


#### 49. How to print all the values of an array? (★★☆)

In [352]:
np.set_printoptions(threshold=1000)

a = np.arange(100)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [ ]:
arr = np.random.randint(1, 100, size=10)
scalar = 10

print(arr)
result = arr[np.argmin(np.abs(scalar - arr))]
print(result)

[20 15 40 33 66 10 58 33 32 75]


np.int64(10)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [361]:
arr = np.zeros(10, [
    ("position", [("x", float, 1), ("y", float, 1)]),
    ("color", [("r", float, 1), ("g", float, 1), ("b", float, 1)]),
])

print(arr)

[(([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))
 (([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))
 (([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))
 (([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))
 (([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [372]:
vec = np.random.random(size=(100, 2))
# print(vec)

X, Y = vec[:, 0], vec[:, 1]

print(X.shape)
print(X[:, np.newaxis].shape)

dist = np.sqrt((X[:, np.newaxis] - X)**2 + (Y[:, np.newaxis] - Y)**2)
print(dist)

(100,)
(100, 1)
[[0.         0.46329042 0.29322288 ... 0.32407432 0.18702968 0.40737867]
 [0.46329042 0.         0.4549868  ... 0.78704391 0.48057777 0.67848578]
 [0.29322288 0.4549868  0.         ... 0.49601041 0.12050419 0.22385109]
 ...
 [0.32407432 0.78704391 0.49601041 ... 0.         0.3821646  0.44758043]
 [0.18702968 0.48057777 0.12050419 ... 0.3821646  0.         0.2373323 ]
 [0.40737867 0.67848578 0.22385109 ... 0.44758043 0.2373323  0.        ]]


In [373]:
# another way

Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.46006552 0.37658728 0.39600013 0.44602423 0.39173968
  0.35278541 0.2373382  0.11858325 0.04793282]
 [0.46006552 0.         0.59267264 0.65173532 0.77498818 0.85178637
  0.70627523 0.28204154 0.44351812 0.50154696]
 [0.37658728 0.59267264 0.         0.0652479  0.79969097 0.54872783
  0.19290484 0.32683816 0.26387751 0.40397218]
 [0.39600013 0.65173532 0.0652479  0.         0.7999022  0.51618426
  0.14411858 0.37992638 0.29203681 0.41681193]
 [0.44602423 0.77498818 0.79969097 0.7999022  0.         0.43184438
  0.70123734 0.65930854 0.56250214 0.40563573]
 [0.39173968 0.85178637 0.54872783 0.51618426 0.43184438 0.
  0.37759512 0.60949568 0.43979504 0.35141096]
 [0.35278541 0.70627523 0.19290484 0.14411858 0.70123734 0.37759512
  0.         0.42424759 0.28262772 0.35722841]
 [0.2373382  0.28204154 0.32683816 0.37992638 0.65930854 0.60949568
  0.42424759 0.         0.17335843 0.2852626 ]
 [0.11858325 0.44351812 0.26387751 0.29203681 0.56250214 0.43979504
  0.28262772 0.17335

#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?

In [ ]:
x = np.array([1, 2, 3, 4], dtype="float32")

x.view(np.int32) # sharesame memory

array([1065353216, 1073741824, 1077936128, 1082130432], dtype=int32)

In [ ]:
x = (np.random.rand(10)*100).astype(np.float32)
print(x)

y = x.view(np.int32)
y[:] = x  # need to assign

print(y)

[30.98525    11.239109    0.38600263 88.759964   15.684301   48.78385
  5.540769   81.1903     75.60737    81.9757    ]
[30 11  0 88 15 48  5 81 75 81]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
from io import StringIO

s = StringIO('''
            1, 2, 3, 4, 5
            6,  ,  , 7, 8
            ,  , 9,10,11
''')

np.genfromtxt(s, delimiter=",", dtype=np.int8)

array([[ 1,  2,  3,  4,  5],
       [ 6, -1, -1,  7,  8],
       [-1, -1,  9, 10, 11]], dtype=int8)

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [399]:
x = np.array([1, 2, 3, 4])

for idx, val in np.ndenumerate(x):
    print(idx, val)

print("*"*8)
# or
for idx in np.ndindex(x.shape):
    print(idx, x[idx])

(0,) 1
(1,) 2
(2,) 3
(3,) 4
********
(0,) 1
(1,) 2
(2,) 3
(3,) 4


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [402]:
"""
Gaussian formula
f(x) = exp(-(x - μ)² / (2σ²))

mean(mu) = 0
std(sigma) = 1
"""

X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
print(X.shape, Y.shape)

mu = 0
sigma = 1
D = np.sqrt(X*X + Y*Y)

G = np.exp((D - mu)**2 / (2 * sigma**2))

print(G)



(10, 10) (10, 10)
[[2.71828183 2.23104288 1.92383577 1.742909   1.65893004 1.65893004
  1.742909   1.92383577 2.23104288 2.71828183]
 [2.23104288 1.83113917 1.57899745 1.43050094 1.36157481 1.36157481
  1.43050094 1.57899745 1.83113917 2.23104288]
 [1.92383577 1.57899745 1.36157481 1.23352576 1.17409053 1.17409053
  1.23352576 1.36157481 1.57899745 1.92383577]
 [1.742909   1.43050094 1.23352576 1.11751907 1.06367341 1.06367341
  1.11751907 1.23352576 1.43050094 1.742909  ]
 [1.65893004 1.36157481 1.17409053 1.06367341 1.0124222  1.0124222
  1.06367341 1.17409053 1.36157481 1.65893004]
 [1.65893004 1.36157481 1.17409053 1.06367341 1.0124222  1.0124222
  1.06367341 1.17409053 1.36157481 1.65893004]
 [1.742909   1.43050094 1.23352576 1.11751907 1.06367341 1.06367341
  1.11751907 1.23352576 1.43050094 1.742909  ]
 [1.92383577 1.57899745 1.36157481 1.23352576 1.17409053 1.17409053
  1.23352576 1.36157481 1.57899745 1.92383577]
 [2.23104288 1.83113917 1.57899745 1.43050094 1.36157481 1.36157

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [411]:
n = 10
Z = np.zeros(shape=(n,n))

np.put(Z, ind=np.random.choice(range(n*n), 3, replace=False), v=1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]]


In [409]:
np.info(np.put)

Replaces specified elements of an array with given values.

The indexing works on the flattened target array. `put` is roughly
equivalent to:

::

    a.flat[ind] = v

Parameters
----------
a : ndarray
    Target array.
ind : array_like
    Target indices, interpreted as integers.
v : array_like
    Values to place in `a` at target indices. If `v` is shorter than
    `ind` it will be repeated as necessary.
mode : {'raise', 'wrap', 'clip'}, optional
    Specifies how out-of-bounds indices will behave.

    * 'raise' -- raise an error (default)
    * 'wrap' -- wrap around
    * 'clip' -- clip to the range

    'clip' mode means that all indices that are too large are replaced
    by the index that addresses the last element along that axis. Note
    that this disables indexing with negative numbers. In 'raise' mode,
    if an exception occurs the target array may still be modified.

See Also
--------
putmask, place
put_along_axis : Put elements by matching the array and the index arrays


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [422]:
np.random.seed(42)

n_rows = 5
n_cols = 5

matrix = np.random.randint(1, 5, size=(n_rows, n_cols))
print(matrix)

means = np.sum(matrix, axis=1) / n_rows
print(means)

result = matrix - means[:, np.newaxis]
print(result)


[[3 4 1 3 3]
 [4 1 1 3 2]
 [3 3 3 3 4]
 [1 4 4 4 3]
 [2 1 2 4 4]]
[2.8 2.2 3.2 3.2 2.6]
[[ 0.2  1.2 -1.8  0.2  0.2]
 [ 1.8 -1.2 -1.2  0.8 -0.2]
 [-0.2 -0.2 -0.2 -0.2  0.8]
 [-2.2  0.8  0.8  0.8 -0.2]
 [-0.6 -1.6 -0.6  1.4  1.4]]


In [ ]:
# another easy way

Y = matrix - matrix.mean(axis=1, keepdims=True)
print(Y)

[[ 0.2  1.2 -1.8  0.2  0.2]
 [ 1.8 -1.2 -1.2  0.8 -0.2]
 [-0.2 -0.2 -0.2 -0.2  0.8]
 [-2.2  0.8  0.8  0.8 -0.2]
 [-0.6 -1.6 -0.6  1.4  1.4]]


#### 59. How to sort an array by the nth column? (★★☆)

In [429]:
np.random.seed(0)
arr = np.random.randint(1, 10, size=(5,5))
print(arr)
print("Sorted by 2nd column:")
print(arr[arr[:, 1].argsort()])


[[6 1 4 4 8]
 [4 6 3 5 8]
 [7 9 9 2 7]
 [8 8 9 2 6]
 [9 5 4 1 4]]
Sorted by 2nd column:
[[6 1 4 4 8]
 [9 5 4 1 4]
 [4 6 3 5 8]
 [8 8 9 2 6]
 [7 9 9 2 7]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [442]:
# one way
np.random.seed(0)
arr1 = np.random.randint(1, 10, size=(5,5))
arr1[:, 3] = 0
print((~Z.any(axis=0)).any())

# another way
arr2 = np.array([
    [0,1,np.nan],
    [1,2,np.nan],
    [4,5,np.nan]
])

np.isnan(arr2).all(axis=0)

True


array([False, False,  True])

#### 61. Find the nearest value from a given value in an array (★★☆)

In [ ]:
np.random.seed(42)
x = np.random.uniform(low=0, high=1, size=10)
print(x)

val = 0.5

# two ways
print(x[np.argmin(np.abs(x-val))])
print(x.flat[np.abs(x-val).argmin()])

[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864 0.15599452
 0.05808361 0.86617615 0.60111501 0.70807258]
0.5986584841970366
0.5986584841970366


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [460]:
np.random.seed(42)
x = np.random.randint(1, 10, size=(1,3))
y = np.random.randint(1, 10, size=(3,1))
print(x, y)
print(x+y)

it = np.nditer([x, y, None])

for x, y, z in it: z[...] = x+y
print(it.operands[2])

[[7 4 8]] [[5]
 [7]
 [3]]
[[12  9 13]
 [14 11 15]
 [10  7 11]]
[[12  9 13]
 [14 11 15]
 [10  7 11]]


#### 63. Create an array class that has a name attribute (★★☆)

In [462]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj

    def __array_finalize__(self, obj):
        if obj is None: return 
        self.name = getattr(obj, "name", "no name")


Z = NamedArray(np.arange(10), "range_10")
print(Z)
print(Z.name)

[0 1 2 3 4 5 6 7 8 9]
range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [465]:
Z = np.ones(10)
I = np.array([1, 2, 3, 4])

Z += np.bincount(I, minlength=len(ones))
print(Z) 

[1. 2. 2. 2. 2. 1. 1. 1. 1. 1.]


In [466]:
np.info(np.bincount)

bincount(x, /, weights=None, minlength=0)

Count number of occurrences of each value in array of non-negative ints.

The number of bins (of size 1) is one larger than the largest value in
`x`. If `minlength` is specified, there will be at least this number
of bins in the output array (though it will be longer if necessary,
depending on the contents of `x`).
Each bin gives the number of occurrences of its index value in `x`.
If `weights` is specified the input array is weighted by it, i.e. if a
value ``n`` is found at position ``i``, ``out[n] += weight[i]`` instead
of ``out[n] += 1``.

Parameters
----------
x : array_like, 1 dimension, nonnegative ints
    Input array.
weights : array_like, optional
    Weights, array of the same shape as `x`.
minlength : int, optional
    A minimum number of bins for the output array.

Returns
-------
out : ndarray of ints
    The result of binning the input array.
    The length of `out` is equal to ``np.amax(x)+1``.

Raises
------
ValueError
    If t

In [469]:
# another way
Z = np.ones(10)
I = np.array([1, 2, 3, 4])
np.add.at(Z, I, 1)
print(Z)

[1. 2. 2. 2. 2. 1. 1. 1. 1. 1.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [477]:
"""
Goal: Add X[i] to F[I[i]] for each i
"""

X = np.array([10, 20, 30, 40, 50])
I = np.array([1, 3, 1, 3, 5])
F = np.zeros(10)

np.add.at(F, I, X)

print(F)

[ 0. 40.  0. 60.  0. 50.  0.  0.  0.  0.]


In [480]:
X = np.array([10, 20, 30, 40, 50])
I = np.array([1, 3, 1, 3, 5])
F = np.bincount(I, weights=X)
print(F)

[ 0. 40.  0. 60.  0. 50.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [ ]:
image = np.random.randint(1, 4, size=(256, 256, 3)).astype("ubyte")

print(image.shape)

len(np.unique(image.reshape((-1, 3)), axis=0))  # find unique rows


(256, 256, 3)


27

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [494]:
arr = np.random.randint(1, 5, size=(2, 2, 2, 2))

print(arr.sum(axis=(-2, -1)))

[[11 13]
 [14 12]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [501]:
np.random.seed(42)

D = np.random.uniform(0,1, 100)
S = np.random.randint(0, 10, 100)

print(D)
print(S)

sums = np.bincount(S, weights=D)  ## weighted sum over the indices in S
print(sums)

counts = np.bincount(S)
print(counts)

means = sums/counts
print("Means:", means)

[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864 0.15599452
 0.05808361 0.86617615 0.60111501 0.70807258 0.02058449 0.96990985
 0.83244264 0.21233911 0.18182497 0.18340451 0.30424224 0.52475643
 0.43194502 0.29122914 0.61185289 0.13949386 0.29214465 0.36636184
 0.45606998 0.78517596 0.19967378 0.51423444 0.59241457 0.04645041
 0.60754485 0.17052412 0.06505159 0.94888554 0.96563203 0.80839735
 0.30461377 0.09767211 0.68423303 0.44015249 0.12203823 0.49517691
 0.03438852 0.9093204  0.25877998 0.66252228 0.31171108 0.52006802
 0.54671028 0.18485446 0.96958463 0.77513282 0.93949894 0.89482735
 0.59789998 0.92187424 0.0884925  0.19598286 0.04522729 0.32533033
 0.38867729 0.27134903 0.82873751 0.35675333 0.28093451 0.54269608
 0.14092422 0.80219698 0.07455064 0.98688694 0.77224477 0.19871568
 0.00552212 0.81546143 0.70685734 0.72900717 0.77127035 0.07404465
 0.35846573 0.11586906 0.86310343 0.62329813 0.33089802 0.06355835
 0.31098232 0.32518332 0.72960618 0.63755747 0.88721274 0.4722

#### 69. How to get the diagonal of a dot product? (★★★)

In [ ]:
np.random.seed(42)

A = np.random.randint(1, 4, size=(3,3))
B = np.random.randint(1, 4, size=(3,3))

prod = np.dot(A, B)
print(prod)

# slow version
print(np.diag(prod))

# fast version: only compute the diagnonal elements
print(sum(A*B.T, axis=1))

[[13 18 17]
 [11 14 13]
 [14 21 19]]
[13 14 19]
[13 14 19]


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [519]:
vec = np.array([1, 2, 3, 4, 5])
cons_zeros = 3

Z = np.zeros(len(vec) + (len(vec)-1) * cons_zeros)
print(len(Z))

Z[::cons_zeros+1] = vec

print(Z)

17
[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)

In [523]:
A = np.random.randint(1, 4, size=(5, 5, 3))
B = np.random.randint(1, 4, size=(5, 5))

prod = A * B[:, :, np.newaxis]
print(prod)


[[[2 2 1]
  [3 2 3]
  [6 4 2]
  [4 2 6]
  [3 3 3]]

 [[9 9 3]
  [3 6 3]
  [4 2 4]
  [6 2 2]
  [3 3 6]]

 [[3 9 9]
  [2 6 2]
  [3 9 3]
  [3 2 1]
  [4 6 4]]

 [[6 9 6]
  [4 6 4]
  [3 2 3]
  [6 4 4]
  [4 2 2]]

 [[2 6 4]
  [6 2 4]
  [3 2 3]
  [4 2 2]
  [4 6 2]]]


#### 72. How to swap two rows of an array? (★★★)

In [525]:
x = np.random.randint(1, 10, size=(5,5))
print(x)

# row to swap
x[[0, 1]] = x[[1, 0]]
print(x)

[[1 1 2 6 9]
 [8 5 1 7 5]
 [6 7 3 3 5]
 [6 9 5 1 4]
 [5 5 7 4 1]]
[[8 5 1 7 5]
 [1 1 2 6 9]
 [6 7 3 3 5]
 [6 9 5 1 4]
 [5 5 7 4 1]]


In [526]:
x[[0, 1]]

array([[8, 5, 1, 7, 5],
       [1, 1, 2, 6, 9]])

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [540]:
np.random.seed(1)

A = np.random.randint(1, 100, (10, 3)) # 10 triplets 

F = np.roll(A.repeat(2, axis=1), -1, axis=1)
F = F.reshape(len(F)*3, 2) # get all edges
F = np.sort(F, axis=1)  # increasing sort to take into account all similar edges

G = F.view(dtype=[('p0',F.dtype),('p1',F.dtype)]) # Reinterprets the data as a structured array with named fields
G = np.unique(G) # get the unique edges

print(len(G))

29


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [547]:
C = np.bincount([1, 1, 2, 3, 4, 4, 6])
print("C:", C)

"""
np.bincount(A) == C
C = [0, 2, 1, 1, 2, 0, 1]

A should have no 0, 2 ones ...
"""

A = np.repeat(np.arange(len(C)), C)   # reapeat vals of array in indices mentioned
print("A:", A)

C: [0 2 1 1 2 0 1]
A: [1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [ ]:
"""
given a sliding window, calculate the mean and move forward
"""

def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]  # get sums of window size n
    return ret[n - 1:] / n  # calculate mean

Z = np.arange(10)
print(moving_average(Z))

[1. 2. 3. 4. 5. 6. 7. 8.]


In [562]:
from numpy.lib.stride_tricks import sliding_window_view

Z = np.arange(10)
print(sliding_window_view(Z, window_shape=3).mean(axis=-1))

[1. 2. 3. 4. 5. 6. 7. 8.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [583]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)

Z = rolling(np.arange(5), 2)
print(Z)

[[0 1]
 [1 2]
 [2 3]
 [3 4]]


In [ ]:
Z = np.arange(5)
print(Z.size)
print(Z.strides[0])

5
8


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [569]:
x = np.array([True])

# inplace op
np.logical_not(x, out=x)

print(x)

[False]


In [571]:
Z = np.random.randint(0,2,100)
print("Before: ", Z)
np.logical_not(Z, out=Z)
print("After: ", Z)

Before:  [1 0 1 0 1 0 0 0 1 1 1 0 1 0 0 0 0 1 0 1 0 1 1 1 0 0 0 0 0 0 1 0 0 1 0 0 1
 1 0 0 0 1 0 0 0 0 1 0 0 0 0 1 1 0 0 1 1 1 0 0 0 0 0 1 1 1 0 1 1 0 0 0 1 1
 0 1 1 1 0 1 1 1 1 0 1 0 0 1 0 1 0 1 1 0 1 1 0 1 1 1]
After:  [0 1 0 1 0 1 1 1 0 0 0 1 0 1 1 1 1 0 1 0 1 0 0 0 1 1 1 1 1 1 0 1 1 0 1 1 0
 0 1 1 1 0 1 1 1 1 0 1 1 1 1 0 0 1 1 0 0 0 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0
 1 0 0 0 1 0 0 0 0 1 0 1 1 0 1 0 1 0 0 1 0 0 1 0 0 0]


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

sns.displot(np.random.uniform(size=1000), kind="kde")

plt.show()

In [ ]:
# what is einsum
# efficinet way to loop and sum over elements

x = np.ones(7)
print(x)

print(np.einsum("i->", x))

# return unsummed axes
x = np.ones((5, 4, 3))
x_ = np.einsum('ijk->kji', x)
print(x_.shape)

[1. 1. 1. 1. 1. 1. 1.]
7.0
(3, 4, 5)


In [48]:
# more einsum

x = np.array([[1, 2], [3, 4]])
print(x)
y = np.array([[1, 2]])

# summation
print(np.einsum("ij->", x))

# column sum
print(np.einsum("ij->j", x))

# row sum
print(np.einsum("ij->i", x))

# matrix multiplication
print(np.einsum("ij, kj->ik", x, y)) # no need to reshape

# matrix matrix multiplication
print(np.einsum("ij, kj->ik", x, x))

# dot product first row with first row of matrix
print(np.einsum("i, i->", x[0], x[0]))

# dot product of matrix
print(np.einsum("ij, ij->", x, x))

# hadamard product (element-wise multiplication)
print(np.einsum("ij, ij->ij", x, x))

# Outer product
a = np.random.rand((3))
b = np.random.rand((5))
print(a, b)
print(np.einsum("i, j->ij", a, b))

# batch matrix multiplication
a = np.random.randn(3, 2, 5)
b = np.random.rand(3, 5, 3)
print(np.einsum("ijk, ikl->ijl", a, b))

# digonal
print(np.einsum("ii->i", x))

# trace
print(np.einsum("ii->", x))

[[1 2]
 [3 4]]
10
[4 6]
[3 7]
[[ 5]
 [11]]
[[ 5 11]
 [11 25]]
5
30
[[ 1  4]
 [ 9 16]]
[0.93436281 0.94296001 0.13595601] [0.34564246 0.82725596 0.8969648  0.67955885 0.76702201]
[[0.32295546 0.7729572  0.83809055 0.63495451 0.71667684]
 [0.32592702 0.78006929 0.84580194 0.64079682 0.72327108]
 [0.04699217 0.11247042 0.12194775 0.09239011 0.10428125]]
[[[-2.13165463 -1.78578104 -0.49913841]
  [-0.15918534 -0.11469242  0.14957355]]

 [[-0.13966367  1.07341864  1.60174903]
  [ 0.08757138 -0.29255751 -0.06230756]]

 [[-2.14176571 -2.91021484 -1.84760175]
  [-0.56188138  0.0472816   0.54382568]]]
[1 4]
5


In [ ]:
P0 = np.random.uniform(-10, 10, (10, 2))
P1 = np.random.uniform(-10, 10, (10, 2))

p = np.array([-5, 5])

def compute_distance(P0, P1, p):
    v = P1- P0 
    v[:,[0,1]] = v[:,[1,0]]
    v[:,1]*=-1 
    norm = np.linalg.norm(v,axis=1)   
    r = P0 - p
    d = np.abs(np.einsum("ij,ij->i",r,v)) / norm 
    return d

print(compute_distance(P0, P1, p))

[ 1.19101151  1.70453485  4.88191785 10.67339036 12.93694601  6.06360478
  3.87564847  3.31661724  4.07388042  6.20437202]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

In [52]:
"""
Rank of matrix:
linearly independant columns
"""

X = np.array(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ]
)

print(np.linalg.matrix_rank(X))

2


In [56]:
# another way with singular value decomposition
U, S, Vt = np.linalg.svd(X)
rank = np.sum(S > 1e-10)
print(rank)

2


#### 83. How to find the most frequent value in an array?

In [59]:
arr = np.array([1,1,1,2,2,3,4,5,5,5,5])
print(np.bincount(arr).argmax())

5


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [66]:
from numpy.lib import stride_tricks

matrix = np.random.randint(1, 5, (10, 10))
print(matrix)

n = 3
i = 1 + (matrix.shape[0]-3)
j = 1 + (matrix.shape[1]-3)
C = stride_tricks.as_strided(matrix, shape=(i, j, n, n), strides=matrix.strides + matrix.strides)
print(C)


[[1 2 1 3 2 1 4 3 2 1]
 [2 3 3 4 3 2 2 3 3 1]
 [4 1 2 3 4 4 3 2 1 3]
 [1 1 3 2 2 2 3 1 3 2]
 [3 4 1 4 1 2 3 2 4 4]
 [4 3 3 4 3 2 1 2 2 4]
 [2 3 2 4 2 3 3 3 1 2]
 [2 3 4 3 4 4 2 1 3 1]
 [4 4 4 4 2 4 4 4 3 2]
 [4 1 2 4 4 3 3 2 2 2]]
[[[[1 2 1]
   [2 3 3]
   [4 1 2]]

  [[2 1 3]
   [3 3 4]
   [1 2 3]]

  [[1 3 2]
   [3 4 3]
   [2 3 4]]

  [[3 2 1]
   [4 3 2]
   [3 4 4]]

  [[2 1 4]
   [3 2 2]
   [4 4 3]]

  [[1 4 3]
   [2 2 3]
   [4 3 2]]

  [[4 3 2]
   [2 3 3]
   [3 2 1]]

  [[3 2 1]
   [3 3 1]
   [2 1 3]]]


 [[[2 3 3]
   [4 1 2]
   [1 1 3]]

  [[3 3 4]
   [1 2 3]
   [1 3 2]]

  [[3 4 3]
   [2 3 4]
   [3 2 2]]

  [[4 3 2]
   [3 4 4]
   [2 2 2]]

  [[3 2 2]
   [4 4 3]
   [2 2 3]]

  [[2 2 3]
   [4 3 2]
   [2 3 1]]

  [[2 3 3]
   [3 2 1]
   [3 1 3]]

  [[3 3 1]
   [2 1 3]
   [1 3 2]]]


 [[[4 1 2]
   [1 1 3]
   [3 4 1]]

  [[1 2 3]
   [1 3 2]
   [4 1 4]]

  [[2 3 4]
   [3 2 2]
   [1 4 1]]

  [[3 4 4]
   [2 2 2]
   [4 1 2]]

  [[4 4 3]
   [2 2 3]
   [1 2 3]]

  [[4 3 2]
   [2 3 1]
   [2 3 

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)